apiVersion: v1
kind: ConfigMap
metadata:
  name: confnginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  2000000;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      keepalive_requests 150000;
      sendfile        on;
      server {
        listen 80;

        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /healthz {
          return 200;
        }

        location / {
          proxy_connect_timeout 10000;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_send_timeout 10000;
          proxy_read_timeout 10000;
          send_timeout 100000;
          proxy_pass http://router.fission.svc.cluster.local;
        }
      }
    }
